### ISSUE TITLE
Warnings with AppCode (intelliJ)

### ISSUE THREAD

**Issue by TiagoVeloso** [ryanmaxwell/UIAlertView-Blocks#20]
I am getting warnings whenever I use UIAlertView+Blocks in AppCode

Somehow the IDE thinks that the method is not implemented because of the "nullable" annotations in the header file.

Don't know if this is relevant or not.

**Comment by TiagoVeloso** [comment]
https://youtrack.jetbrains.com/issue/OC-11672

It's their fault, after all.

**Comment by ryanmaxwell** [comment]
Yep this is the third third or fourth issue I've had reported on this. I never knew so many people used app code! Are you mandated to use it for work, or do you actually like it?

**Comment by TiagoVeloso** [comment]
I actually like for code writing. The refactoring and stub generation tools are much better than xcode's.

Interface building and project managing are somewhat easier with xcode. So I guess I use both IDEs. But when I have to implement logic I prefer appcode. 

Since I also develop for Android switching from iOS to android isn't as hard. Since android studio is also based in IntelliJ.

**Comment by ryanmaxwell** [comment]
ok thanks for the insight! I prefer to use Apple's tools, so that i'm not left behind when new features come out (like this one). But I agree - Refactoring in Xcode needs some assistance. It's always been weak for Obj-c, and is currently non-existent for Swift. Eclipse is damn ugly, but it sure knows how to refactor Java!
